### ISSUE TITLE
Userinterface freezes if you scan twice [sf#17]

### ISSUE THREAD

**Issue by kolomiets** [twain/twain-cs#21]
**Reported by propperdx on 2015-11-27 14:23 UTC**
With enabled userinterface the userinterface freezes if you try to scan the second time. I tried two different scanners. 

e.g. twaincsscan.exe, TWAINCS Version 02.03.02.00

**Comment by yongqitao** [comment]
My question is the same as yours. How did you solve it in the end?

**Comment by gisCDL** [comment]
My question is the same as yours. How did you solve it in the end?

**Comment by mlmcl62** [comment]
these kinds of issues were resolved when the toolkit was removed...
