### ISSUE TITLE
twain print not happening with messages CAP_PRINTERSTRING,CAP_PRINTERSUFFIX

### ISSUE THREAD

**Issue by vijaynet10** [twain/twain-cs#31]
Hai ,

We bought epson plq 22cs passbook printer , we trying to integrate with our dotnet application using twain-cs.
 
 requirement
 
 1. Reading Bar-code value from passbook
 2. Without ejecting the passbook have to print some lines 
 3. Eject the passbook
 
From the above requirement, we have done the steps 1 and 3.But  print is not happening.We tried with CAP_PRINTERSTRING,CAP_PRINTERSUFFIX messages .We need your support to solve this issue.

**Comment by mlmcl62** [comment]
The application needs to confirm through CAP_SUPPORTEDCAPS that both CAP_PRINTERSTRING and CAP_PRINTERSUFFIX are supported.  If they are, then following the Capability Ordering section in the TWAIN Specification, the application must first set CAP_PRINTERENABLED to TRUE.  Then any other printing capability items may be negotiated.  All of this happens in state 4, with printing occurring during scanning.  If the scanner being used differs from this behavior it will be necessary to contact the vendor for additional help...

**Comment by vijaynet10** [comment]
do you have any samples in dotnet @mlmcl62
