### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by wswszm** [twain/twain-cs#37]
hello! i'm a develop from chinese.i want to know how to use this ,do u have a  document of it about how to use this for scanner. And how can i use this without defaut scanner parameter form.The another question is How to use scanner to sweep paper continuously.Much obliged for your assistance

**Comment by mattzirkle** [comment]
I'm not an owner of this repository, but I did investigate using this for a project I worked on. This is meant more of an example of how one might create a TWAIN application on a Windows Form application in C#.NET. If you are looking to build an application from scratch, you should become VERY familiar with the TWAIN specification, which can be found on the [TWAIN Working Group website](https://www.twain.org/specification/). If you are looking for more of a library/framework to help you get started, I would recommend also checking out [NTWAIN](https://github.com/soukoku/ntwain).
