### ISSUE TITLE
No Twain driver found

### ISSUE THREAD

**Issue by boobigbam** [twain/twain-cs#39]
Hi
I get a "There are no Twain drivers installed on this system" error from the FormScan.cs.
Anyone who can hint me to why I get this error?
Thanks

(I have run other Twain test projects and they do find my scanners, so I know I have Twain compatible scanners.)
(I'm a casual programmer with basic knowledge in .net so I might be missing some simple point here:-)

**Comment by makingbloke** [comment]
Is it possible your app is running 64bit and you’ve got a 32bit driver
installed? This will cause the issue you describe. Vice versa (32bit app
and 64bit Twain is also the case)

Cheers

**Comment by boobigbam** [comment]
Thanks for your comment, im sure your are right about that.
Could i ask if you got any hint as to how i solve that problem:-)

**Comment by makingbloke** [comment]
In your project settings in visual studio make the platform target x86.

The other more convoluted route I took is to write a small console app that
does the scanner work. Compile this as 32bit then launch and talk to it
from your main app (which can be compiled to any CPU).

Cheers

**Comment by boobigbam** [comment]
Ahh super found that.
Thanks very much

**Comment by mlmcl62** [comment]
solved by a friendly helper
