### ISSUE TITLE
missing definition for TWAIN.Enum_TryParse

### ISSUE THREAD

**Issue by dskinner** [twain/twain-cs#54]
It appears in https://github.com/twain/twain-cs/commit/74fe02ed78a689a8cc42b4d9e74cf1e47107e6a4 there was a swap from `Enum.TryParse` to `TWAIN.Enum_TryParse` but a definition for such was not also included in the commit.

**Comment by mlmcl62** [comment]
Bit of .NET 2.0 snuck in on me from another file.  It's been addressed...
